@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package lol.roxxane.roxxys_survival_core.commands.recipes;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;