@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package lol.roxxane.roxxys_survival_core.blocks.state_property_enums;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;