@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package lol.roxxane.roxxys_survival_core;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;