@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package lol.roxxane.roxxys_survival_core.commands.recipes.filtering_v2;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;