@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package lol.roxxane.roxxys_survival_core.mob_effects;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;